-- Squashed schema baseline for the portfolio/dev database.
-- Generated from the current PostgreSQL schema; demo data is inserted by DataInitializer.

--
-- PostgreSQL database dump
--


-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--



SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account (
    email_verified boolean NOT NULL,
    account_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email_verify_expires_at timestamp(6) without time zone,
    role character varying(20) NOT NULL,
    status character varying(20),
    email_verify_token character varying(100),
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    CONSTRAINT account_role_check CHECK (((role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'PARTNER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: account_account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin (
    account_id bigint NOT NULL,
    admin_created_at timestamp(6) without time zone NOT NULL,
    admin_id bigint NOT NULL,
    admin_status character varying(20) NOT NULL,
    admin_name character varying(255) NOT NULL,
    CONSTRAINT admin_admin_status_check CHECK (((admin_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


--
-- Name: admin_admin_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin ALTER COLUMN admin_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_event_reward; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_event_reward (
    created_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    event_no bigint NOT NULL,
    order_item_no bigint NOT NULL,
    point_amount bigint NOT NULL,
    reward_no bigint NOT NULL
);


--
-- Name: admin_event_reward_order_cap; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_event_reward_order_cap (
    cap_no bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    event_no bigint NOT NULL,
    order_no bigint NOT NULL
);


--
-- Name: admin_event_reward_order_cap_cap_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin_event_reward_order_cap ALTER COLUMN cap_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_event_reward_order_cap_cap_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_event_reward_reward_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin_event_reward ALTER COLUMN reward_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_event_reward_reward_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brand; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.brand (
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    code character varying(100) NOT NULL,
    country character varying(100),
    canonical_name character varying(200) NOT NULL,
    display_name character varying(200) NOT NULL,
    slug character varying(200),
    logo_url character varying(300)
);


--
-- Name: cart; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart (
    cart_created_at timestamp(6) without time zone NOT NULL,
    cart_no bigint NOT NULL,
    cart_updated_at timestamp(6) without time zone,
    customer_id bigint NOT NULL
);


--
-- Name: cart_cart_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart ALTER COLUMN cart_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_cart_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_item (
    quantity integer NOT NULL,
    cart_item_created_at timestamp(6) without time zone NOT NULL,
    cart_item_no bigint NOT NULL,
    cart_item_updated_at timestamp(6) without time zone,
    cart_no bigint NOT NULL,
    item_price bigint NOT NULL,
    option_no bigint,
    product_no bigint NOT NULL
);


--
-- Name: cart_item_cart_item_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_item ALTER COLUMN cart_item_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_item_cart_item_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: color; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.color (
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    hex character varying(7),
    code character varying(50) NOT NULL,
    label character varying(100) NOT NULL
);


--
-- Name: color_synonym; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.color_synonym (
    id bigint NOT NULL,
    color_code character varying(50) NOT NULL,
    synonym character varying(100) NOT NULL
);


--
-- Name: color_synonym_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.color_synonym ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.color_synonym_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer (
    customer_birth date NOT NULL,
    email_checked boolean NOT NULL,
    total_order_count integer NOT NULL,
    account_id bigint NOT NULL,
    customer_create_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    grade_id bigint,
    point_balance bigint NOT NULL,
    token_expiry_at timestamp(6) without time zone,
    total_purchase_amount bigint NOT NULL,
    email_check_token character varying(100),
    customer_email character varying(255) NOT NULL,
    customer_name character varying(255) NOT NULL,
    customer_password character varying(255) NOT NULL
);


--
-- Name: customer_activity_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_activity_log (
    activity_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    log_id bigint NOT NULL,
    activity_type character varying(50) NOT NULL,
    ip_address character varying(50),
    user_agent character varying(500),
    activity_details text,
    CONSTRAINT customer_activity_log_activity_type_check CHECK (((activity_type)::text = ANY ((ARRAY['LOGIN'::character varying, 'LOGOUT'::character varying, 'ORDER_CREATED'::character varying, 'ORDER_CANCELLED'::character varying, 'ORDER_COMPLETED'::character varying, 'REVIEW_CREATED'::character varying, 'REVIEW_UPDATED'::character varying, 'REVIEW_DELETED'::character varying, 'RETURN_REQUESTED'::character varying, 'RETURN_APPROVED'::character varying, 'RETURN_REJECTED'::character varying, 'RETURN_COMPLETED'::character varying, 'PROFILE_UPDATED'::character varying, 'PASSWORD_CHANGED'::character varying, 'EMAIL_VERIFIED'::character varying, 'ADDRESS_ADDED'::character varying, 'ADDRESS_UPDATED'::character varying, 'ADDRESS_DELETED'::character varying])::text[])))
);


--
-- Name: customer_activity_log_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_activity_log ALTER COLUMN log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_activity_log_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_address; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_address (
    is_default boolean NOT NULL,
    address_no bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    delivery_address character varying(255) NOT NULL,
    delivery_address_detail character varying(255),
    delivery_zip_code character varying(255),
    recipient_name character varying(255) NOT NULL,
    recipient_phone character varying(255) NOT NULL
);


--
-- Name: customer_address_address_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_address ALTER COLUMN address_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_address_address_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer ALTER COLUMN customer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_grade; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_grade (
    discount_rate double precision NOT NULL,
    grade_level integer NOT NULL,
    is_active boolean NOT NULL,
    min_order_count integer NOT NULL,
    point_accumulation_rate double precision NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    grade_id bigint NOT NULL,
    min_purchase_amount bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    grade_name character varying(50) NOT NULL,
    CONSTRAINT customer_grade_grade_name_check CHECK (((grade_name)::text = ANY ((ARRAY['BEGINNER'::character varying, 'SWIMMER'::character varying, 'PRO'::character varying, 'MASTER'::character varying, 'LEGEND'::character varying])::text[])))
);


--
-- Name: customer_grade_grade_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_grade ALTER COLUMN grade_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_grade_grade_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_history (
    admin_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    history_id bigint NOT NULL,
    action_type character varying(50) NOT NULL,
    reason character varying(1000),
    new_value character varying(2000),
    old_value character varying(2000),
    CONSTRAINT customer_history_action_type_check CHECK (((action_type)::text = ANY ((ARRAY['INFO_UPDATE'::character varying, 'STATUS_ACTIVATE'::character varying, 'STATUS_DEACTIVATE'::character varying, 'PASSWORD_RESET'::character varying, 'EMAIL_VERIFICATION_RESEND'::character varying])::text[])))
);


--
-- Name: customer_history_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_history ALTER COLUMN history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_history_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_note; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_note (
    is_important boolean NOT NULL,
    admin_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    note_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    note_content text NOT NULL
);


--
-- Name: customer_note_note_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_note ALTER COLUMN note_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_note_note_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_tag (
    created_at timestamp(6) without time zone NOT NULL,
    tag_id bigint NOT NULL,
    tag_color character varying(20) NOT NULL,
    tag_name character varying(50) NOT NULL,
    description character varying(200)
);


--
-- Name: customer_tag_mapping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_tag_mapping (
    customer_id bigint NOT NULL,
    mapping_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


--
-- Name: customer_tag_mapping_mapping_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_tag_mapping ALTER COLUMN mapping_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_tag_mapping_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_tag_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_tag ALTER COLUMN tag_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_tag_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: delivery; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.delivery (
    delivery_end_date timestamp(6) without time zone,
    delivery_no bigint NOT NULL,
    delivery_start_date timestamp(6) without time zone,
    order_item_no bigint NOT NULL,
    delivery_courier character varying(255),
    delivery_status character varying(255) NOT NULL,
    delivery_tracking_number character varying(255),
    CONSTRAINT delivery_delivery_status_check CHECK (((delivery_status)::text = ANY ((ARRAY['READY'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying])::text[])))
);


--
-- Name: delivery_delivery_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.delivery ALTER COLUMN delivery_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delivery_delivery_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event (
    partner_apply_enabled boolean NOT NULL,
    admin_no bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    customer_event_end_at timestamp(6) without time zone NOT NULL,
    customer_event_start_at timestamp(6) without time zone NOT NULL,
    event_no bigint NOT NULL,
    partner_apply_end_at timestamp(6) without time zone,
    partner_apply_start_at timestamp(6) without time zone,
    point_event_min_order_amount bigint,
    sale_discount_value bigint,
    sale_max_discount_amount bigint,
    updated_at timestamp(6) without time zone NOT NULL,
    event_status character varying(20) NOT NULL,
    sale_discount_type character varying(20),
    event_mode character varying(30),
    event_type character varying(30),
    point_event_target_type character varying(30),
    event_title character varying(200) NOT NULL,
    thumbnail_url character varying(500),
    admin_memo character varying(1000),
    point_event_target_value character varying(1000),
    event_content character varying(4000) NOT NULL,
    customer_expose_at timestamp(6) without time zone,
    CONSTRAINT event_event_mode_check CHECK (((event_mode)::text = ANY ((ARRAY['ADMIN_ONLY'::character varying, 'PARTNER_PARTICIPATION'::character varying])::text[]))),
    CONSTRAINT event_event_status_check CHECK (((event_status)::text = ANY ((ARRAY['PRIVATE'::character varying, 'PUBLISHED'::character varying, 'ENDED'::character varying])::text[]))),
    CONSTRAINT event_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['SALE'::character varying, 'POINT'::character varying, 'COUPON'::character varying, 'GIFT'::character varying])::text[]))),
    CONSTRAINT event_point_event_target_type_check CHECK (((point_event_target_type)::text = ANY ((ARRAY['ALL'::character varying, 'PARTNER'::character varying, 'PRODUCT'::character varying, 'OPTION'::character varying, 'CATEGORY'::character varying, 'MIN_ORDER_AMOUNT'::character varying])::text[]))),
    CONSTRAINT event_sale_discount_type_check CHECK (((sale_discount_type)::text = ANY ((ARRAY['PERCENT'::character varying, 'FIXED'::character varying])::text[])))
);


--
-- Name: event_event_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.event ALTER COLUMN event_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_event_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_point_target; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_point_target (
    created_at timestamp(6) without time zone NOT NULL,
    event_no bigint NOT NULL,
    id bigint NOT NULL,
    target_type character varying(30) NOT NULL,
    target_value character varying(100) NOT NULL,
    CONSTRAINT event_point_target_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['ALL'::character varying, 'PARTNER'::character varying, 'PRODUCT'::character varying, 'OPTION'::character varying, 'CATEGORY'::character varying, 'MIN_ORDER_AMOUNT'::character varying])::text[])))
);


--
-- Name: event_point_target_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.event_point_target ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_point_target_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: faq; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.faq (
    admin_id bigint NOT NULL,
    faq_no bigint NOT NULL,
    faq_answer character varying(255) NOT NULL,
    faq_category character varying(255) NOT NULL,
    faq_question character varying(255) NOT NULL
);


--
-- Name: faq_faq_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.faq ALTER COLUMN faq_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.faq_faq_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory (
    inventory_stock integer NOT NULL,
    inventory_no bigint NOT NULL,
    option_no bigint,
    product_no bigint
);


--
-- Name: inventory_inventory_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory ALTER COLUMN inventory_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_inventory_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: option; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.option (
    option_add_price bigint,
    option_no bigint NOT NULL,
    original_option_add_price bigint,
    partner_id bigint NOT NULL,
    product_no bigint NOT NULL,
    option_status character varying(20) NOT NULL,
    color character varying(255),
    original_color character varying(255),
    original_size character varying(255),
    size character varying(255),
    CONSTRAINT option_option_status_check CHECK (((option_status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACTIVE'::character varying, 'REJECTED'::character varying, 'INACTIVE'::character varying, 'PENDING_UPDATE'::character varying])::text[])))
);


--
-- Name: option_option_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.option ALTER COLUMN option_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.option_option_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_item (
    is_cancelled boolean NOT NULL,
    item_quantity integer NOT NULL,
    applied_sale_event_no bigint,
    applied_sale_policy_no bigint,
    completed_at timestamp(6) without time zone,
    confirmed_at timestamp(6) without time zone,
    event_snapshot_locked_at timestamp(6) without time zone,
    item_discount_amount bigint NOT NULL,
    item_price bigint NOT NULL,
    item_total_price bigint NOT NULL,
    option_no bigint,
    order_item_no bigint NOT NULL,
    order_no bigint NOT NULL,
    product_no bigint NOT NULL,
    sale_evaluated_at timestamp(6) without time zone,
    applied_sale_event_type character varying(30),
    applied_sale_campaign_id character varying(100),
    admin_event_snapshot character varying(1000),
    partner_event_snapshot character varying(1000),
    admin_event_policy_snapshot text,
    partner_event_policy_snapshot text,
    CONSTRAINT order_item_applied_sale_event_type_check CHECK (((applied_sale_event_type)::text = ANY ((ARRAY['SALE'::character varying, 'POINT'::character varying, 'COUPON'::character varying, 'GIFT'::character varying])::text[])))
);


--
-- Name: order_item_order_item_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_item ALTER COLUMN order_item_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_item_order_item_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    customer_id bigint NOT NULL,
    order_created_at timestamp(6) without time zone NOT NULL,
    order_no bigint NOT NULL,
    order_total_price bigint NOT NULL,
    used_point_amount bigint NOT NULL,
    order_memo character varying(1000),
    delivery_address character varying(255) NOT NULL,
    delivery_address_detail character varying(255),
    delivery_zip_code character varying(255),
    order_status character varying(255) NOT NULL,
    payment_method character varying(255) NOT NULL,
    recipient_name character varying(255) NOT NULL,
    recipient_phone character varying(255) NOT NULL,
    CONSTRAINT orders_order_status_check CHECK (((order_status)::text = ANY ((ARRAY['PENDING_PAYMENT'::character varying, 'PAID'::character varying, 'PAYMENT_FAILED'::character varying, 'ACTIVE'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: orders_order_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN order_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partner; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partner (
    account_id bigint,
    admin_id bigint NOT NULL,
    bank_account_file_id bigint,
    business_registration_file_id bigint,
    deactivation_rejected_at timestamp(6) without time zone,
    deactivation_requested_at timestamp(6) without time zone,
    partner_approved_at timestamp(6) without time zone,
    partner_id bigint NOT NULL,
    reactivation_rejected_at timestamp(6) without time zone,
    reactivation_requested_at timestamp(6) without time zone,
    business_registration_number character varying(12) NOT NULL,
    partner_contact character varying(20) NOT NULL,
    partner_status character varying(20) NOT NULL,
    partner_bank_account character varying(50) NOT NULL,
    representative_brand_code character varying(100),
    deactivation_rejection_reason character varying(500),
    deactivation_request_reason character varying(500),
    reactivation_rejection_reason character varying(500),
    reactivation_request_reason character varying(500),
    rejection_reason character varying(500),
    email character varying(255),
    partner_name character varying(255) NOT NULL,
    CONSTRAINT partner_partner_status_check CHECK (((partner_status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'INACTIVE'::character varying])::text[])))
);


--
-- Name: partner_change_request; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partner_change_request (
    created_at timestamp(6) without time zone NOT NULL,
    partner_id bigint NOT NULL,
    processed_admin_id bigint,
    processed_at timestamp(6) without time zone,
    request_id bigint NOT NULL,
    requested_business_registration_number character varying(12),
    status character varying(20) NOT NULL,
    requested_partner_bank_account character varying(50),
    requested_partner_name character varying(100),
    requested_representative_brand_code character varying(100),
    reject_reason character varying(1000),
    request_reason character varying(1000),
    CONSTRAINT partner_change_request_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: partner_change_request_request_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.partner_change_request ALTER COLUMN request_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partner_change_request_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partner_event_participation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partner_event_participation (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    event_no bigint NOT NULL,
    id bigint NOT NULL,
    partner_id bigint NOT NULL,
    scope character varying(30) NOT NULL,
    CONSTRAINT partner_event_participation_scope_check CHECK (((scope)::text = 'STORE_LEVEL'::text))
);


--
-- Name: partner_event_participation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.partner_event_participation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partner_event_participation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partner_event_reward; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partner_event_reward (
    created_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    event_no bigint NOT NULL,
    order_item_no bigint NOT NULL,
    partner_id bigint NOT NULL,
    point_amount bigint NOT NULL,
    reward_no bigint NOT NULL
);


--
-- Name: partner_event_reward_order_cap; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partner_event_reward_order_cap (
    cap_no bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    event_no bigint NOT NULL,
    order_no bigint NOT NULL
);


--
-- Name: partner_event_reward_order_cap_cap_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.partner_event_reward_order_cap ALTER COLUMN cap_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partner_event_reward_order_cap_cap_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partner_event_reward_reward_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.partner_event_reward ALTER COLUMN reward_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partner_event_reward_reward_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partner_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partner_history (
    admin_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    history_id bigint NOT NULL,
    partner_id bigint NOT NULL,
    from_status character varying(20),
    to_status character varying(20),
    action_type character varying(50) NOT NULL,
    reason character varying(1000),
    CONSTRAINT partner_history_action_type_check CHECK (((action_type)::text = ANY ((ARRAY['APPLICATION'::character varying, 'APPROVAL'::character varying, 'REJECTION'::character varying, 'DEACTIVATION_REQUEST'::character varying, 'DEACTIVATION_APPROVED'::character varying, 'DEACTIVATION_REJECTION'::character varying, 'REACTIVATION_REQUEST'::character varying, 'REACTIVATION_APPROVED'::character varying, 'REACTIVATION_REJECTION'::character varying, 'DEACTIVATED'::character varying, 'ACTIVATED'::character varying])::text[]))),
    CONSTRAINT partner_history_from_status_check CHECK (((from_status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'INACTIVE'::character varying])::text[]))),
    CONSTRAINT partner_history_to_status_check CHECK (((to_status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'INACTIVE'::character varying])::text[])))
);


--
-- Name: partner_history_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.partner_history ALTER COLUMN history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partner_history_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partner_partner_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.partner ALTER COLUMN partner_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partner_partner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partner_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partner_profile (
    partner_id bigint NOT NULL,
    profile_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    customer_service_phone character varying(20),
    contact_person_name character varying(100),
    profile_image_url character varying(500),
    introduction character varying(2000)
);


--
-- Name: partner_profile_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.partner_profile ALTER COLUMN profile_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partner_profile_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment (
    payment_cancel_yn boolean NOT NULL,
    order_no bigint,
    paid_at timestamp(6) without time zone,
    payment_amount bigint NOT NULL,
    payment_created_at timestamp(6) without time zone NOT NULL,
    payment_no bigint NOT NULL,
    status character varying(30),
    provider character varying(50),
    payment_key character varying(200),
    pg_order_id character varying(200),
    fail_reason character varying(500),
    receipt_url character varying(500),
    payment_method character varying(255) NOT NULL,
    raw_approve_payload text,
    CONSTRAINT payment_status_check CHECK (((status)::text = ANY ((ARRAY['READY'::character varying, 'PAID'::character varying, 'CANCELED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: payment_payment_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment ALTER COLUMN payment_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_payment_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_webhook_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_webhook_log (
    processed boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    processed_at timestamp(6) without time zone,
    type character varying(100),
    event_id character varying(200) NOT NULL,
    error_message character varying(500),
    signature character varying(500),
    payload text
);


--
-- Name: payment_webhook_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment_webhook_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_webhook_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: point_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.point_history (
    expire_date date,
    admin_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    history_id bigint NOT NULL,
    order_item_no bigint,
    order_no bigint,
    point_amount bigint NOT NULL,
    point_balance_after bigint NOT NULL,
    description character varying(500),
    point_type character varying(255) NOT NULL,
    CONSTRAINT point_history_point_type_check CHECK (((point_type)::text = ANY ((ARRAY['ACCUMULATE'::character varying, 'USE'::character varying, 'MANUAL_ADD'::character varying, 'MANUAL_DEDUCT'::character varying, 'EXPIRE'::character varying])::text[])))
);


--
-- Name: point_history_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.point_history ALTER COLUMN history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.point_history_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product (
    partner_id bigint,
    product_created_at timestamp(6) without time zone NOT NULL,
    product_no bigint NOT NULL,
    product_updated_at timestamp(6) without time zone,
    rejection_reason character varying(1000),
    original_product_description text,
    original_product_image_url character varying(255),
    original_product_name character varying(255),
    original_product_price character varying(255),
    original_product_sub_type character varying(255),
    original_product_type character varying(255),
    product_active_status character varying(255) NOT NULL,
    product_description text NOT NULL,
    product_image_url character varying(255) NOT NULL,
    product_name character varying(255) NOT NULL,
    product_price character varying(255) NOT NULL,
    product_sub_type character varying(255),
    product_type character varying(255) NOT NULL,
    brand_name character varying(100),
    design_name character varying(200),
    manufacture_country character varying(100),
    material_info character varying(1000),
    origin_country character varying(100),
    original_brand_name character varying(100),
    original_design_name character varying(200),
    original_manufacture_country character varying(100),
    original_material_info character varying(1000),
    original_origin_country character varying(100),
    original_sku character varying(100),
    sku character varying(100),
    care_instructions character varying(1000),
    original_care_instructions character varying(1000),
    original_size_guide_text text,
    size_guide_text text,
    original_size_guide_json text,
    size_guide_json text,
    CONSTRAINT product_original_product_sub_type_check CHECK (((original_product_sub_type)::text = ANY ((ARRAY['ONE_PIECE'::character varying, 'BIKINI'::character varying, 'MONOKINI'::character varying, 'RASH_GUARD'::character varying, 'TRUNKS'::character varying, 'JAMMER'::character varying, 'BRIEF'::character varying, 'CAP_SILICONE'::character varying, 'CAP_FABRIC'::character varying, 'FINS_SHORT'::character varying, 'FINS_LONG'::character varying, 'NONE'::character varying])::text[]))),
    CONSTRAINT product_original_product_type_check CHECK (((original_product_type)::text = ANY ((ARRAY['SWIMSUIT_MEN'::character varying, 'SWIMSUIT_WOMEN'::character varying, 'SWIMSUIT_KIDS'::character varying, 'SWIM_CAP'::character varying, 'SWIM_GOGGLES'::character varying, 'FINS'::character varying, 'SWIM_TOY'::character varying, 'ETC'::character varying])::text[]))),
    CONSTRAINT product_product_active_status_check CHECK (((product_active_status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACTIVE'::character varying, 'REJECTED'::character varying, 'INACTIVE'::character varying, 'PENDING_UPDATE'::character varying])::text[]))),
    CONSTRAINT product_product_sub_type_check CHECK (((product_sub_type)::text = ANY ((ARRAY['ONE_PIECE'::character varying, 'BIKINI'::character varying, 'MONOKINI'::character varying, 'RASH_GUARD'::character varying, 'TRUNKS'::character varying, 'JAMMER'::character varying, 'BRIEF'::character varying, 'CAP_SILICONE'::character varying, 'CAP_FABRIC'::character varying, 'FINS_SHORT'::character varying, 'FINS_LONG'::character varying, 'NONE'::character varying])::text[]))),
    CONSTRAINT product_product_type_check CHECK (((product_type)::text = ANY ((ARRAY['SWIMSUIT_MEN'::character varying, 'SWIMSUIT_WOMEN'::character varying, 'SWIMSUIT_KIDS'::character varying, 'SWIM_CAP'::character varying, 'SWIM_GOGGLES'::character varying, 'FINS'::character varying, 'SWIM_TOY'::character varying, 'ETC'::character varying])::text[])))
);


--
-- Name: product_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_image (
    is_primary boolean NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    file_id bigint,
    id bigint NOT NULL,
    product_no bigint NOT NULL,
    image_url character varying(1000) NOT NULL
);


--
-- Name: product_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_product_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product ALTER COLUMN product_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_product_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_view; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_view (
    product_no bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    view_count bigint NOT NULL
);


--
-- Name: product_view_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_view_log (
    id bigint NOT NULL,
    customer_id bigint,
    guest_id character varying(100),
    product_no bigint NOT NULL,
    viewed_at timestamp(6) without time zone NOT NULL
);


--
-- Name: product_view_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_view_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_view_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: return; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.return (
    return_risk_score integer,
    order_item_no bigint NOT NULL,
    return_amount bigint NOT NULL,
    return_no bigint NOT NULL,
    return_requested_at timestamp(6) without time zone NOT NULL,
    return_risk_tier character varying(20),
    return_reason_type character varying(32) NOT NULL,
    rejection_reason character varying(1000),
    return_reason character varying(1000),
    return_courier character varying(255),
    return_status character varying(255) NOT NULL,
    return_tracking_number character varying(255),
    CONSTRAINT return_return_reason_type_check CHECK (((return_reason_type)::text = ANY ((ARRAY['CHANGE_OF_MIND'::character varying, 'DEFECT'::character varying, 'WRONG_ITEM'::character varying, 'ORDER_MISTAKE'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT return_return_risk_tier_check CHECK (((return_risk_tier)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying])::text[]))),
    CONSTRAINT return_return_status_check CHECK (((return_status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'PICKUP_COMPLETED'::character varying, 'REFUNDED'::character varying])::text[])))
);


--
-- Name: return_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.return_history (
    admin_id bigint,
    changed_at timestamp(6) without time zone NOT NULL,
    history_id bigint NOT NULL,
    partner_id bigint,
    return_no bigint NOT NULL,
    action_type character varying(50) NOT NULL,
    reason character varying(500),
    new_value character varying(1000),
    old_value character varying(1000)
);


--
-- Name: return_history_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.return_history ALTER COLUMN history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.return_history_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: return_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.return_image (
    file_id bigint NOT NULL,
    id bigint NOT NULL,
    return_no bigint NOT NULL,
    image_url character varying(1000) NOT NULL
);


--
-- Name: return_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.return_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.return_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: return_return_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.return ALTER COLUMN return_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.return_return_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: return_risk_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.return_risk_log (
    score double precision NOT NULL,
    success boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    latency_ms bigint NOT NULL,
    option_no bigint,
    product_no bigint,
    risk_level character varying(20) NOT NULL,
    model character varying(50),
    error_message character varying(1000),
    request_payload text,
    response_payload text
);


--
-- Name: return_risk_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.return_risk_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.return_risk_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review (
    review_rating integer NOT NULL,
    customer_id bigint NOT NULL,
    order_item_no bigint NOT NULL,
    product_no bigint NOT NULL,
    review_created_at timestamp(6) without time zone NOT NULL,
    review_no bigint NOT NULL,
    review_reply_created_at timestamp(6) without time zone,
    review_content character varying(1000) NOT NULL,
    review_reply character varying(1000),
    CONSTRAINT review_review_rating_check CHECK (((review_rating <= 5) AND (review_rating >= 1)))
);


--
-- Name: review_analysis_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review_analysis_log (
    success boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    from_at timestamp(6) without time zone,
    id bigint NOT NULL,
    latency_ms bigint NOT NULL,
    to_at timestamp(6) without time zone,
    model character varying(50),
    partner_id character varying(100),
    error_message character varying(1000),
    product_nos_payload text,
    request_payload text,
    response_payload text
);


--
-- Name: review_analysis_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review_analysis_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_analysis_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review_image (
    file_id bigint NOT NULL,
    id bigint NOT NULL,
    review_no bigint NOT NULL,
    image_url character varying(1000) NOT NULL
);


--
-- Name: review_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_review_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review ALTER COLUMN review_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_review_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sale_policy; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sale_policy (
    admin_no bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by_partner_id bigint,
    discount_value bigint NOT NULL,
    end_at timestamp(6) without time zone NOT NULL,
    event_no bigint,
    id bigint NOT NULL,
    max_discount_amount bigint,
    start_at timestamp(6) without time zone NOT NULL,
    target_option_no bigint,
    target_product_no bigint,
    updated_at timestamp(6) without time zone NOT NULL,
    discount_type character varying(20) NOT NULL,
    scope character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    rejection_reason character varying(500),
    campaign_id character varying(255),
    CONSTRAINT sale_policy_discount_type_check CHECK (((discount_type)::text = ANY ((ARRAY['PERCENT'::character varying, 'FIXED'::character varying])::text[]))),
    CONSTRAINT sale_policy_scope_check CHECK (((scope)::text = ANY ((ARRAY['PRODUCT'::character varying, 'OPTION'::character varying])::text[]))),
    CONSTRAINT sale_policy_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING_APPROVAL'::character varying, 'ACTIVE'::character varying, 'INACTIVE'::character varying, 'REJECTED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: sale_policy_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sale_policy_history (
    after_event_no bigint,
    before_event_no bigint,
    changed_at timestamp(6) without time zone NOT NULL,
    changed_by_id bigint NOT NULL,
    history_id bigint NOT NULL,
    sale_policy_id bigint NOT NULL,
    after_status character varying(20),
    before_status character varying(20),
    changed_by_role character varying(20) NOT NULL,
    action character varying(30) NOT NULL,
    reason character varying(500),
    CONSTRAINT sale_policy_history_action_check CHECK (((action)::text = ANY ((ARRAY['EVENT_LINK_CHANGED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying, 'PARTICIPATION_DEACTIVATED'::character varying, 'PARTICIPATION_REACTIVATED'::character varying])::text[]))),
    CONSTRAINT sale_policy_history_after_status_check CHECK (((after_status)::text = ANY ((ARRAY['PENDING_APPROVAL'::character varying, 'ACTIVE'::character varying, 'INACTIVE'::character varying, 'REJECTED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT sale_policy_history_before_status_check CHECK (((before_status)::text = ANY ((ARRAY['PENDING_APPROVAL'::character varying, 'ACTIVE'::character varying, 'INACTIVE'::character varying, 'REJECTED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT sale_policy_history_changed_by_role_check CHECK (((changed_by_role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'PARTNER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: sale_policy_history_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sale_policy_history ALTER COLUMN history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_policy_history_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sale_policy_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sale_policy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_policy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settlement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settlement (
    settlement_created_at date NOT NULL,
    settlement_paid_date date,
    settlement_period_end date,
    settlement_period_start date,
    admin_id bigint NOT NULL,
    commission_amount bigint NOT NULL,
    partner_id bigint NOT NULL,
    settlement_amount bigint NOT NULL,
    settlement_id bigint NOT NULL,
    total_sales_amount bigint NOT NULL,
    settlement_status character varying(255) NOT NULL,
    CONSTRAINT settlement_settlement_status_check CHECK (((settlement_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: settlement_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settlement_history (
    admin_id bigint NOT NULL,
    changed_at timestamp(6) without time zone NOT NULL,
    history_id bigint NOT NULL,
    settlement_id bigint NOT NULL,
    action_type character varying(50) NOT NULL,
    reason character varying(500),
    new_value character varying(1000),
    old_value character varying(1000)
);


--
-- Name: settlement_history_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.settlement_history ALTER COLUMN history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlement_history_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settlement_order_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settlement_order_item (
    id bigint NOT NULL,
    order_item_no bigint NOT NULL,
    settlement_id bigint NOT NULL
);


--
-- Name: settlement_order_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.settlement_order_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlement_order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settlement_settlement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.settlement ALTER COLUMN settlement_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlement_settlement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: size; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.size (
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    code character varying(50) NOT NULL,
    label character varying(100) NOT NULL
);


--
-- Name: size_synonym; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.size_synonym (
    id bigint NOT NULL,
    size_code character varying(50) NOT NULL,
    synonym character varying(100) NOT NULL
);


--
-- Name: size_synonym_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.size_synonym ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.size_synonym_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: uploaded_file; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.uploaded_file (
    is_private boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    file_id bigint NOT NULL,
    size bigint NOT NULL,
    uploaded_by_subject_id bigint NOT NULL,
    uploaded_by_role character varying(20) NOT NULL,
    category character varying(50) NOT NULL,
    content_type character varying(100) NOT NULL,
    storage_path character varying(1000) NOT NULL,
    original_name character varying(255) NOT NULL,
    stored_name character varying(255) NOT NULL,
    CONSTRAINT uploaded_file_uploaded_by_role_check CHECK (((uploaded_by_role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'PARTNER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: uploaded_file_file_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.uploaded_file ALTER COLUMN file_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uploaded_file_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account account_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_email_key UNIQUE (email);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (account_id);


--
-- Name: admin admin_account_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_account_id_key UNIQUE (account_id);


--
-- Name: admin_event_reward admin_event_reward_event_no_order_item_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_event_reward
    ADD CONSTRAINT admin_event_reward_event_no_order_item_no_key UNIQUE (event_no, order_item_no);


--
-- Name: admin_event_reward_order_cap admin_event_reward_order_cap_event_no_customer_id_order_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_event_reward_order_cap
    ADD CONSTRAINT admin_event_reward_order_cap_event_no_customer_id_order_no_key UNIQUE (event_no, customer_id, order_no);


--
-- Name: admin_event_reward_order_cap admin_event_reward_order_cap_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_event_reward_order_cap
    ADD CONSTRAINT admin_event_reward_order_cap_pkey PRIMARY KEY (cap_no);


--
-- Name: admin_event_reward admin_event_reward_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_event_reward
    ADD CONSTRAINT admin_event_reward_pkey PRIMARY KEY (reward_no);


--
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (admin_id);


--
-- Name: brand brand_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.brand
    ADD CONSTRAINT brand_pkey PRIMARY KEY (code);


--
-- Name: cart cart_customer_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_customer_id_key UNIQUE (customer_id);


--
-- Name: cart_item cart_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT cart_item_pkey PRIMARY KEY (cart_item_no);


--
-- Name: cart cart_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_pkey PRIMARY KEY (cart_no);


--
-- Name: color color_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.color
    ADD CONSTRAINT color_pkey PRIMARY KEY (code);


--
-- Name: color_synonym color_synonym_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.color_synonym
    ADD CONSTRAINT color_synonym_pkey PRIMARY KEY (id);


--
-- Name: customer customer_account_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_account_id_key UNIQUE (account_id);


--
-- Name: customer_activity_log customer_activity_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_activity_log
    ADD CONSTRAINT customer_activity_log_pkey PRIMARY KEY (log_id);


--
-- Name: customer_address customer_address_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_address
    ADD CONSTRAINT customer_address_pkey PRIMARY KEY (address_no);


--
-- Name: customer_grade customer_grade_grade_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_grade
    ADD CONSTRAINT customer_grade_grade_name_key UNIQUE (grade_name);


--
-- Name: customer_grade customer_grade_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_grade
    ADD CONSTRAINT customer_grade_pkey PRIMARY KEY (grade_id);


--
-- Name: customer_history customer_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_history
    ADD CONSTRAINT customer_history_pkey PRIMARY KEY (history_id);


--
-- Name: customer_note customer_note_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_note
    ADD CONSTRAINT customer_note_pkey PRIMARY KEY (note_id);


--
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (customer_id);


--
-- Name: customer_tag_mapping customer_tag_mapping_customer_id_tag_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_tag_mapping
    ADD CONSTRAINT customer_tag_mapping_customer_id_tag_id_key UNIQUE (customer_id, tag_id);


--
-- Name: customer_tag_mapping customer_tag_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_tag_mapping
    ADD CONSTRAINT customer_tag_mapping_pkey PRIMARY KEY (mapping_id);


--
-- Name: customer_tag customer_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_tag
    ADD CONSTRAINT customer_tag_pkey PRIMARY KEY (tag_id);


--
-- Name: customer_tag customer_tag_tag_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_tag
    ADD CONSTRAINT customer_tag_tag_name_key UNIQUE (tag_name);


--
-- Name: delivery delivery_order_item_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery
    ADD CONSTRAINT delivery_order_item_no_key UNIQUE (order_item_no);


--
-- Name: delivery delivery_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery
    ADD CONSTRAINT delivery_pkey PRIMARY KEY (delivery_no);


--
-- Name: event event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT event_pkey PRIMARY KEY (event_no);


--
-- Name: event_point_target event_point_target_event_no_target_type_target_value_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_point_target
    ADD CONSTRAINT event_point_target_event_no_target_type_target_value_key UNIQUE (event_no, target_type, target_value);


--
-- Name: event_point_target event_point_target_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_point_target
    ADD CONSTRAINT event_point_target_pkey PRIMARY KEY (id);


--
-- Name: faq faq_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faq
    ADD CONSTRAINT faq_pkey PRIMARY KEY (faq_no);


--
-- Name: payment_webhook_log idx_webhook_event_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_webhook_log
    ADD CONSTRAINT idx_webhook_event_id UNIQUE (event_id);


--
-- Name: inventory inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_pkey PRIMARY KEY (inventory_no);


--
-- Name: option option_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.option
    ADD CONSTRAINT option_pkey PRIMARY KEY (option_no);


--
-- Name: order_item order_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_pkey PRIMARY KEY (order_item_no);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (order_no);


--
-- Name: partner partner_account_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner
    ADD CONSTRAINT partner_account_id_key UNIQUE (account_id);


--
-- Name: partner_change_request partner_change_request_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_change_request
    ADD CONSTRAINT partner_change_request_pkey PRIMARY KEY (request_id);


--
-- Name: partner_event_participation partner_event_participation_partner_id_event_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_event_participation
    ADD CONSTRAINT partner_event_participation_partner_id_event_no_key UNIQUE (partner_id, event_no);


--
-- Name: partner_event_participation partner_event_participation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_event_participation
    ADD CONSTRAINT partner_event_participation_pkey PRIMARY KEY (id);


--
-- Name: partner_event_reward partner_event_reward_event_no_order_item_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_event_reward
    ADD CONSTRAINT partner_event_reward_event_no_order_item_no_key UNIQUE (event_no, order_item_no);


--
-- Name: partner_event_reward_order_cap partner_event_reward_order_ca_event_no_customer_id_order_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_event_reward_order_cap
    ADD CONSTRAINT partner_event_reward_order_ca_event_no_customer_id_order_no_key UNIQUE (event_no, customer_id, order_no);


--
-- Name: partner_event_reward_order_cap partner_event_reward_order_cap_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_event_reward_order_cap
    ADD CONSTRAINT partner_event_reward_order_cap_pkey PRIMARY KEY (cap_no);


--
-- Name: partner_event_reward partner_event_reward_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_event_reward
    ADD CONSTRAINT partner_event_reward_pkey PRIMARY KEY (reward_no);


--
-- Name: partner_history partner_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_history
    ADD CONSTRAINT partner_history_pkey PRIMARY KEY (history_id);


--
-- Name: partner partner_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner
    ADD CONSTRAINT partner_pkey PRIMARY KEY (partner_id);


--
-- Name: partner_profile partner_profile_partner_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_profile
    ADD CONSTRAINT partner_profile_partner_id_key UNIQUE (partner_id);


--
-- Name: partner_profile partner_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_profile
    ADD CONSTRAINT partner_profile_pkey PRIMARY KEY (profile_id);


--
-- Name: payment payment_order_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_order_no_key UNIQUE (order_no);


--
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (payment_no);


--
-- Name: payment_webhook_log payment_webhook_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_webhook_log
    ADD CONSTRAINT payment_webhook_log_pkey PRIMARY KEY (id);


--
-- Name: point_history point_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.point_history
    ADD CONSTRAINT point_history_pkey PRIMARY KEY (history_id);


--
-- Name: product_image product_image_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_image
    ADD CONSTRAINT product_image_pkey PRIMARY KEY (id);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (product_no);


--
-- Name: product_view_log product_view_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_view_log
    ADD CONSTRAINT product_view_log_pkey PRIMARY KEY (id);


--
-- Name: product_view product_view_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_view
    ADD CONSTRAINT product_view_pkey PRIMARY KEY (product_no);


--
-- Name: return_history return_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_history
    ADD CONSTRAINT return_history_pkey PRIMARY KEY (history_id);


--
-- Name: return_image return_image_file_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_image
    ADD CONSTRAINT return_image_file_id_key UNIQUE (file_id);


--
-- Name: return_image return_image_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_image
    ADD CONSTRAINT return_image_pkey PRIMARY KEY (id);


--
-- Name: return return_order_item_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return
    ADD CONSTRAINT return_order_item_no_key UNIQUE (order_item_no);


--
-- Name: return return_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return
    ADD CONSTRAINT return_pkey PRIMARY KEY (return_no);


--
-- Name: return_risk_log return_risk_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_risk_log
    ADD CONSTRAINT return_risk_log_pkey PRIMARY KEY (id);


--
-- Name: review_analysis_log review_analysis_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_analysis_log
    ADD CONSTRAINT review_analysis_log_pkey PRIMARY KEY (id);


--
-- Name: review_image review_image_file_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_image
    ADD CONSTRAINT review_image_file_id_key UNIQUE (file_id);


--
-- Name: review_image review_image_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_image
    ADD CONSTRAINT review_image_pkey PRIMARY KEY (id);


--
-- Name: review review_order_item_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_order_item_no_key UNIQUE (order_item_no);


--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (review_no);


--
-- Name: sale_policy_history sale_policy_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_policy_history
    ADD CONSTRAINT sale_policy_history_pkey PRIMARY KEY (history_id);


--
-- Name: sale_policy sale_policy_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_policy
    ADD CONSTRAINT sale_policy_pkey PRIMARY KEY (id);


--
-- Name: settlement_history settlement_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_history
    ADD CONSTRAINT settlement_history_pkey PRIMARY KEY (history_id);


--
-- Name: settlement_order_item settlement_order_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_order_item
    ADD CONSTRAINT settlement_order_item_pkey PRIMARY KEY (id);


--
-- Name: settlement settlement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement
    ADD CONSTRAINT settlement_pkey PRIMARY KEY (settlement_id);


--
-- Name: size size_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.size
    ADD CONSTRAINT size_pkey PRIMARY KEY (code);


--
-- Name: size_synonym size_synonym_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.size_synonym
    ADD CONSTRAINT size_synonym_pkey PRIMARY KEY (id);


--
-- Name: event_point_target uk55ft5eni4mhomtn94pauhtal7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_point_target
    ADD CONSTRAINT uk55ft5eni4mhomtn94pauhtal7 UNIQUE (event_no, target_type, target_value);


--
-- Name: admin_event_reward_order_cap uk8dq3lrqk125p7tetvwv8s0aph; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_event_reward_order_cap
    ADD CONSTRAINT uk8dq3lrqk125p7tetvwv8s0aph UNIQUE (event_no, customer_id, order_no);


--
-- Name: color_synonym uk_color_synonym_value; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.color_synonym
    ADD CONSTRAINT uk_color_synonym_value UNIQUE (synonym);


--
-- Name: review uk_review_order_item; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT uk_review_order_item UNIQUE (order_item_no);


--
-- Name: size_synonym uk_size_synonym_value; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.size_synonym
    ADD CONSTRAINT uk_size_synonym_value UNIQUE (synonym);


--
-- Name: partner_event_reward_order_cap ukcjdyonwn2jx498y8wmi0sgt22; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_event_reward_order_cap
    ADD CONSTRAINT ukcjdyonwn2jx498y8wmi0sgt22 UNIQUE (event_no, customer_id, order_no);


--
-- Name: customer_tag_mapping ukhc594vncvxwngso9njjx0jf8y; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_tag_mapping
    ADD CONSTRAINT ukhc594vncvxwngso9njjx0jf8y UNIQUE (customer_id, tag_id);


--
-- Name: partner_event_participation ukl6upuurvyjj8rd737hbn2pylo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_event_participation
    ADD CONSTRAINT ukl6upuurvyjj8rd737hbn2pylo UNIQUE (partner_id, event_no);


--
-- Name: partner_event_reward ukoe66tbkamuxa1t22tvcux7bi0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_event_reward
    ADD CONSTRAINT ukoe66tbkamuxa1t22tvcux7bi0 UNIQUE (event_no, order_item_no);


--
-- Name: account ukq0uja26qgu1atulenwup9rxyr; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT ukq0uja26qgu1atulenwup9rxyr UNIQUE (email);


--
-- Name: admin_event_reward ukqdxaspxdkno146cw2ece5jnku; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_event_reward
    ADD CONSTRAINT ukqdxaspxdkno146cw2ece5jnku UNIQUE (event_no, order_item_no);


--
-- Name: uploaded_file uploaded_file_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.uploaded_file
    ADD CONSTRAINT uploaded_file_pkey PRIMARY KEY (file_id);


--
-- Name: uploaded_file uploaded_file_stored_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.uploaded_file
    ADD CONSTRAINT uploaded_file_stored_name_key UNIQUE (stored_name);


--
-- Name: size_synonym fk1g0tjj094dy4iurfvya15hxl7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.size_synonym
    ADD CONSTRAINT fk1g0tjj094dy4iurfvya15hxl7 FOREIGN KEY (size_code) REFERENCES public.size(code);


--
-- Name: partner_history fk1k49joxvtc5l1acq47o4b5b50; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_history
    ADD CONSTRAINT fk1k49joxvtc5l1acq47o4b5b50 FOREIGN KEY (partner_id) REFERENCES public.partner(partner_id);


--
-- Name: admin_event_reward fk1sbjem19fgqw0705xpt6l4cu3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_event_reward
    ADD CONSTRAINT fk1sbjem19fgqw0705xpt6l4cu3 FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


--
-- Name: review_image fk1w12aeij5n35n95gvfurtuaxj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_image
    ADD CONSTRAINT fk1w12aeij5n35n95gvfurtuaxj FOREIGN KEY (review_no) REFERENCES public.review(review_no);


--
-- Name: partner_event_participation fk2ivlmvck0fkjwayyyvykshy8h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_event_participation
    ADD CONSTRAINT fk2ivlmvck0fkjwayyyvykshy8h FOREIGN KEY (event_no) REFERENCES public.event(event_no);


--
-- Name: inventory fk3772iujx3ihc8fsmbvjwrthhs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT fk3772iujx3ihc8fsmbvjwrthhs FOREIGN KEY (product_no) REFERENCES public.product(product_no);


--
-- Name: settlement_history fk3b53epebqd2j4k0k2fdpwrpyu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_history
    ADD CONSTRAINT fk3b53epebqd2j4k0k2fdpwrpyu FOREIGN KEY (settlement_id) REFERENCES public.settlement(settlement_id);


--
-- Name: customer_history fk3x6m569xyqqexparqbhhy6w98; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_history
    ADD CONSTRAINT fk3x6m569xyqqexparqbhhy6w98 FOREIGN KEY (admin_id) REFERENCES public.admin(admin_id);


--
-- Name: partner_event_participation fk48reionmeicwujbuy901gx6km; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_event_participation
    ADD CONSTRAINT fk48reionmeicwujbuy901gx6km FOREIGN KEY (partner_id) REFERENCES public.partner(partner_id);


--
-- Name: orders fk624gtjin3po807j3vix093tlf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk624gtjin3po807j3vix093tlf FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


--
-- Name: partner fk6252kc7uww1oq4otdf04jyfi7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner
    ADD CONSTRAINT fk6252kc7uww1oq4otdf04jyfi7 FOREIGN KEY (account_id) REFERENCES public.account(account_id);


--
-- Name: order_item fk64yctpiamtrlkbdp6lc626cy3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT fk64yctpiamtrlkbdp6lc626cy3 FOREIGN KEY (order_no) REFERENCES public.orders(order_no);


--
-- Name: settlement_order_item fk67f3m2ty2img3gnad7vjh3u5s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_order_item
    ADD CONSTRAINT fk67f3m2ty2img3gnad7vjh3u5s FOREIGN KEY (order_item_no) REFERENCES public.order_item(order_item_no);


--
-- Name: customer_tag_mapping fk6x6v51lp31r9eklonlqy62bic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_tag_mapping
    ADD CONSTRAINT fk6x6v51lp31r9eklonlqy62bic FOREIGN KEY (tag_id) REFERENCES public.customer_tag(tag_id);


--
-- Name: point_history fk7bpnpboxysn3thylch3iinho2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.point_history
    ADD CONSTRAINT fk7bpnpboxysn3thylch3iinho2 FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


--
-- Name: admin_event_reward_order_cap fk86npc6kmdlseaetk1jr0in4c7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_event_reward_order_cap
    ADD CONSTRAINT fk86npc6kmdlseaetk1jr0in4c7 FOREIGN KEY (event_no) REFERENCES public.event(event_no);


--
-- Name: partner_event_reward fk9swlo4omamjr1ho56khen35qt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_event_reward
    ADD CONSTRAINT fk9swlo4omamjr1ho56khen35qt FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


--
-- Name: partner_change_request fka4xpklboa3gxu8763tkunl14p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_change_request
    ADD CONSTRAINT fka4xpklboa3gxu8763tkunl14p FOREIGN KEY (processed_admin_id) REFERENCES public.admin(admin_id);


--
-- Name: customer_history fkad84kkpqlnakuqd9qdxhbie3y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_history
    ADD CONSTRAINT fkad84kkpqlnakuqd9qdxhbie3y FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


--
-- Name: delivery fkayemihkpxyx2r2pnrgbpki6a0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery
    ADD CONSTRAINT fkayemihkpxyx2r2pnrgbpki6a0 FOREIGN KEY (order_item_no) REFERENCES public.order_item(order_item_no);


--
-- Name: faq fkbkcgd68depr066fi6pgj4nntq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faq
    ADD CONSTRAINT fkbkcgd68depr066fi6pgj4nntq FOREIGN KEY (admin_id) REFERENCES public.admin(admin_id);


--
-- Name: cart_item fkc09yxkl9ncjmg114t9rb6mltq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT fkc09yxkl9ncjmg114t9rb6mltq FOREIGN KEY (cart_no) REFERENCES public.cart(cart_no);


--
-- Name: settlement fkcjd7bpkcyhuo7h7n4udj9dh35; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement
    ADD CONSTRAINT fkcjd7bpkcyhuo7h7n4udj9dh35 FOREIGN KEY (partner_id) REFERENCES public.partner(partner_id);


--
-- Name: admin_event_reward fkckd1bjdm9adsus2wkofna5jqc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_event_reward
    ADD CONSTRAINT fkckd1bjdm9adsus2wkofna5jqc FOREIGN KEY (event_no) REFERENCES public.event(event_no);


--
-- Name: partner_event_reward fkcxh1da1byn2cpog92jcd70ljm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_event_reward
    ADD CONSTRAINT fkcxh1da1byn2cpog92jcd70ljm FOREIGN KEY (event_no) REFERENCES public.event(event_no);


--
-- Name: return fkdcyy7qra99s931ifgulh82p4x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return
    ADD CONSTRAINT fkdcyy7qra99s931ifgulh82p4x FOREIGN KEY (order_item_no) REFERENCES public.order_item(order_item_no);


--
-- Name: cart fkdebwvad6pp1ekiqy5jtixqbaj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT fkdebwvad6pp1ekiqy5jtixqbaj FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


--
-- Name: return_image fkdh6hvy7ni1h4ryf3dtdgnml6u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_image
    ADD CONSTRAINT fkdh6hvy7ni1h4ryf3dtdgnml6u FOREIGN KEY (return_no) REFERENCES public.return(return_no);


--
-- Name: return_image fkdxs9cacobau0o02vy3xsa34jp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_image
    ADD CONSTRAINT fkdxs9cacobau0o02vy3xsa34jp FOREIGN KEY (file_id) REFERENCES public.uploaded_file(file_id);


--
-- Name: customer fke8h665q9eyd1fj7wn0p6jnld9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT fke8h665q9eyd1fj7wn0p6jnld9 FOREIGN KEY (grade_id) REFERENCES public.customer_grade(grade_id);


--
-- Name: settlement fkeypildvo6d688c7o6t4dhibqe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement
    ADD CONSTRAINT fkeypildvo6d688c7o6t4dhibqe FOREIGN KEY (admin_id) REFERENCES public.admin(admin_id);


--
-- Name: sale_policy_history fkg1udoykrt1hkub6butwpqnh9v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_policy_history
    ADD CONSTRAINT fkg1udoykrt1hkub6butwpqnh9v FOREIGN KEY (sale_policy_id) REFERENCES public.sale_policy(id);


--
-- Name: review fkgce54o0p6uugoc2tev4awewly; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fkgce54o0p6uugoc2tev4awewly FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


--
-- Name: customer_tag_mapping fkh5y9n5q6m305g5lsi8x2i30w4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_tag_mapping
    ADD CONSTRAINT fkh5y9n5q6m305g5lsi8x2i30w4 FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


--
-- Name: settlement_order_item fkhmirbnyyf7n0d8f7lib1cim74; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_order_item
    ADD CONSTRAINT fkhmirbnyyf7n0d8f7lib1cim74 FOREIGN KEY (settlement_id) REFERENCES public.settlement(settlement_id);


--
-- Name: review fkhuoic095mwi7ehk4oxwwhpuvq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fkhuoic095mwi7ehk4oxwwhpuvq FOREIGN KEY (product_no) REFERENCES public.product(product_no);


--
-- Name: order_item fkikhr28ut8p8qq3f33lhi643fu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT fkikhr28ut8p8qq3f33lhi643fu FOREIGN KEY (product_no) REFERENCES public.product(product_no);


--
-- Name: inventory fkjfswydhmpibk6ueh2quvl49xt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT fkjfswydhmpibk6ueh2quvl49xt FOREIGN KEY (option_no) REFERENCES public.option(option_no);


--
-- Name: sale_policy fkjoswg3b54qgtosce5jp6vbudc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_policy
    ADD CONSTRAINT fkjoswg3b54qgtosce5jp6vbudc FOREIGN KEY (event_no) REFERENCES public.event(event_no);


--
-- Name: partner_change_request fkjvae08p7ga2ytmvbo4ji8y6xq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_change_request
    ADD CONSTRAINT fkjvae08p7ga2ytmvbo4ji8y6xq FOREIGN KEY (partner_id) REFERENCES public.partner(partner_id);


--
-- Name: event fkjymeb24dih8w55s7cnvful0xv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT fkjymeb24dih8w55s7cnvful0xv FOREIGN KEY (admin_no) REFERENCES public.admin(admin_id);


--
-- Name: partner_history fkl20dp2egnbvh1fx6ygiveyekm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_history
    ADD CONSTRAINT fkl20dp2egnbvh1fx6ygiveyekm FOREIGN KEY (admin_id) REFERENCES public.admin(admin_id);


--
-- Name: review fkl2q091krkt3qu64es8redbjj8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fkl2q091krkt3qu64es8redbjj8 FOREIGN KEY (order_item_no) REFERENCES public.order_item(order_item_no);


--
-- Name: partner_profile fkli662m69qfxe90800ocwpooq2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_profile
    ADD CONSTRAINT fkli662m69qfxe90800ocwpooq2 FOREIGN KEY (partner_id) REFERENCES public.partner(partner_id);


--
-- Name: settlement_history fkmsslfsor2anr58jcl6gg07q2n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_history
    ADD CONSTRAINT fkmsslfsor2anr58jcl6gg07q2n FOREIGN KEY (admin_id) REFERENCES public.admin(admin_id);


--
-- Name: admin_event_reward_order_cap fkmu46cuggg04o2klvyjiulub4l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_event_reward_order_cap
    ADD CONSTRAINT fkmu46cuggg04o2klvyjiulub4l FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


--
-- Name: customer_note fkn10gn22kpirfysv8bkt2mwt64; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_note
    ADD CONSTRAINT fkn10gn22kpirfysv8bkt2mwt64 FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


--
-- Name: admin fkn2eatyxq78i3wg18tt0jf56lw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT fkn2eatyxq78i3wg18tt0jf56lw FOREIGN KEY (account_id) REFERENCES public.account(account_id);


--
-- Name: customer fkn9x2k8svpxj3r328iy1rpur83; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT fkn9x2k8svpxj3r328iy1rpur83 FOREIGN KEY (account_id) REFERENCES public.account(account_id);


--
-- Name: order_item fknafcd8iqgcfeq32nyutwm106d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT fknafcd8iqgcfeq32nyutwm106d FOREIGN KEY (option_no) REFERENCES public.option(option_no);


--
-- Name: option fknaq3r0pgt6rdo9ofmkny8cqs6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.option
    ADD CONSTRAINT fknaq3r0pgt6rdo9ofmkny8cqs6 FOREIGN KEY (partner_id) REFERENCES public.partner(partner_id);


--
-- Name: point_history fknllvtsfjcus3qus4vb9lxvbna; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.point_history
    ADD CONSTRAINT fknllvtsfjcus3qus4vb9lxvbna FOREIGN KEY (admin_id) REFERENCES public.admin(admin_id);


--
-- Name: return_history fkp3rldo56etv0rmlv49uf18ii1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_history
    ADD CONSTRAINT fkp3rldo56etv0rmlv49uf18ii1 FOREIGN KEY (partner_id) REFERENCES public.partner(partner_id);


--
-- Name: payment fkp5jkucblp7k64r9kacabu7mj8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fkp5jkucblp7k64r9kacabu7mj8 FOREIGN KEY (order_no) REFERENCES public.orders(order_no);


--
-- Name: customer_activity_log fkp5x694ysvrnu2mi6wbq8dh3h0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_activity_log
    ADD CONSTRAINT fkp5x694ysvrnu2mi6wbq8dh3h0 FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


--
-- Name: partner_event_reward_order_cap fkpa38dpiggo0op15emtoylol6s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_event_reward_order_cap
    ADD CONSTRAINT fkpa38dpiggo0op15emtoylol6s FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


--
-- Name: product_image fkpodwshyyfx9pxukth4anuvlcv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_image
    ADD CONSTRAINT fkpodwshyyfx9pxukth4anuvlcv FOREIGN KEY (product_no) REFERENCES public.product(product_no);


--
-- Name: event_point_target fkpq40kit27q4yoydxifd0honrx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_point_target
    ADD CONSTRAINT fkpq40kit27q4yoydxifd0honrx FOREIGN KEY (event_no) REFERENCES public.event(event_no);


--
-- Name: color_synonym fkpwa84q03mmoarktxaok40scbq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.color_synonym
    ADD CONSTRAINT fkpwa84q03mmoarktxaok40scbq FOREIGN KEY (color_code) REFERENCES public.color(code);


--
-- Name: return_history fkq4muvk5fjooplqfmne2025dih; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_history
    ADD CONSTRAINT fkq4muvk5fjooplqfmne2025dih FOREIGN KEY (return_no) REFERENCES public.return(return_no);


--
-- Name: customer_note fkqxxw1mm9t9rgnglm22aipg9ai; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_note
    ADD CONSTRAINT fkqxxw1mm9t9rgnglm22aipg9ai FOREIGN KEY (admin_id) REFERENCES public.admin(admin_id);


--
-- Name: cart_item fkr2fa1a7k9sntcdgv97ed5n4qn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT fkr2fa1a7k9sntcdgv97ed5n4qn FOREIGN KEY (option_no) REFERENCES public.option(option_no);


--
-- Name: customer_address fkr9ofa0ydsgbaqmt9leb3v5eii; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_address
    ADD CONSTRAINT fkr9ofa0ydsgbaqmt9leb3v5eii FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


--
-- Name: product fkrauw3xtfxqf4h5crj8s8nniwj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fkrauw3xtfxqf4h5crj8s8nniwj FOREIGN KEY (partner_id) REFERENCES public.partner(partner_id);


--
-- Name: review_image fkrcobd838scmt7fyc404m3jsqp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_image
    ADD CONSTRAINT fkrcobd838scmt7fyc404m3jsqp FOREIGN KEY (file_id) REFERENCES public.uploaded_file(file_id);


--
-- Name: return_history fkrcunaf8ai9ey68x9s2f8apu77; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_history
    ADD CONSTRAINT fkrcunaf8ai9ey68x9s2f8apu77 FOREIGN KEY (admin_id) REFERENCES public.admin(admin_id);


--
-- Name: partner_event_reward_order_cap fkre9lnpj14epyx40u6unkr67m1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_event_reward_order_cap
    ADD CONSTRAINT fkre9lnpj14epyx40u6unkr67m1 FOREIGN KEY (event_no) REFERENCES public.event(event_no);


--
-- Name: cart_item fks7n4m1ul7lnp5f9x1mr8gm90k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT fks7n4m1ul7lnp5f9x1mr8gm90k FOREIGN KEY (product_no) REFERENCES public.product(product_no);


--
-- Name: sale_policy fkssjaxwwmvptd5m8ltj6skt7yd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_policy
    ADD CONSTRAINT fkssjaxwwmvptd5m8ltj6skt7yd FOREIGN KEY (admin_no) REFERENCES public.admin(admin_id);


--
-- Name: partner fkt91418kfru39rw4r8qad2nhk1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner
    ADD CONSTRAINT fkt91418kfru39rw4r8qad2nhk1 FOREIGN KEY (admin_id) REFERENCES public.admin(admin_id);


--
-- Name: option fktfpa2ixsgcuh3bq518gg28yn1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.option
    ADD CONSTRAINT fktfpa2ixsgcuh3bq518gg28yn1 FOREIGN KEY (product_no) REFERENCES public.product(product_no);


--
-- PostgreSQL database dump complete
--


