CREATE TABLE public.qna (
    qna_no bigint NOT NULL,
    customer_id bigint NOT NULL,
    category character varying(32) NOT NULL,
    scope character varying(32),
    status character varying(32) NOT NULL,
    title character varying(255) NOT NULL,
    order_no bigint,
    order_item_no bigint,
    partner_id bigint,
    return_no bigint,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    answered_at timestamp(6) without time zone
);

ALTER TABLE public.qna ALTER COLUMN qna_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qna_qna_no_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.qna
    ADD CONSTRAINT qna_pkey PRIMARY KEY (qna_no);

ALTER TABLE ONLY public.qna
    ADD CONSTRAINT fk_qna_customer FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);

ALTER TABLE ONLY public.qna
    ADD CONSTRAINT fk_qna_order FOREIGN KEY (order_no) REFERENCES public.orders(order_no);

ALTER TABLE ONLY public.qna
    ADD CONSTRAINT fk_qna_order_item FOREIGN KEY (order_item_no) REFERENCES public.order_item(order_item_no);

ALTER TABLE ONLY public.qna
    ADD CONSTRAINT fk_qna_partner FOREIGN KEY (partner_id) REFERENCES public.partner(partner_id);

ALTER TABLE ONLY public.qna
    ADD CONSTRAINT fk_qna_return FOREIGN KEY (return_no) REFERENCES public.return(return_no);

CREATE TABLE public.qna_message (
    message_no bigint NOT NULL,
    qna_no bigint NOT NULL,
    author_type character varying(32) NOT NULL,
    author_admin_id bigint,
    author_partner_id bigint,
    body text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);

ALTER TABLE public.qna_message ALTER COLUMN message_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qna_message_message_no_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.qna_message
    ADD CONSTRAINT qna_message_pkey PRIMARY KEY (message_no);

ALTER TABLE ONLY public.qna_message
    ADD CONSTRAINT fk_qna_message_qna FOREIGN KEY (qna_no) REFERENCES public.qna(qna_no);

ALTER TABLE ONLY public.qna_message
    ADD CONSTRAINT fk_qna_message_admin FOREIGN KEY (author_admin_id) REFERENCES public.admin(admin_id);

ALTER TABLE ONLY public.qna_message
    ADD CONSTRAINT fk_qna_message_partner FOREIGN KEY (author_partner_id) REFERENCES public.partner(partner_id);

CREATE INDEX idx_qna_customer ON public.qna (customer_id);
CREATE INDEX idx_qna_partner ON public.qna (partner_id);
CREATE INDEX idx_qna_status ON public.qna (status);
CREATE INDEX idx_qna_message_qna ON public.qna_message (qna_no);
